FROM ghcr.io/zalando/spilo-16:3.3-p1

ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

USER root
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    python3 -m pip install --no-cache-dir etcd3 "protobuf==3.19.6" && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /home/postgres/pgdata/pgroot && \
    chown -R postgres:postgres /home/postgres/pgdata && \
    chmod 777 /home/postgres/pgdata/pgroot

USER postgres
